# Generated by Django 2.2.17 on 2021-01-21 19:03

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0056_remote_rate_limit'),
    ]

    operations = [
        migrations.AddField(
            model_name='repository',
            name='publish_settings',
            field=django.contrib.postgres.fields.jsonb.JSONField(null=True),
        ),
    ]
